# Generated by Django 2.2.16 on 2020-10-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productname', models.CharField(max_length=200)),
                ('Productprize', models.FloatField(max_length=5000)),
                ('Shopname', models.CharField(max_length=200)),
            ],
        ),
    ]
