# Generated by Django 2.2.16 on 2020-10-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Productquantity',
            field=models.CharField(default='some_value', max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='Productname',
            field=models.CharField(default='some_value', max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='Productprize',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='Shopname',
            field=models.CharField(default='some_value', max_length=200),
        ),
    ]
