# Generated by Django 2.2.16 on 2020-10-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0002_auto_20201031_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Productimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
