# Generated by Django 2.2.16 on 2020-10-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0004_addtocard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Productimage',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
