# Generated by Django 2.2.16 on 2020-10-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0005_auto_20201031_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Productimage',
            field=models.CharField(default='some_value', max_length=200),
        ),
    ]
