# Generated by Django 2.2.16 on 2020-10-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0006_auto_20201031_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Productimage',
            field=models.CharField(default='some_value', max_length=200, null=True),
        ),
    ]
