# Generated by Django 3.1.4 on 2021-02-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0008_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
